version: '3'
services:
  app:
    image: maven:3.6.0-jdk-8-alpine
    working_dir: /app
    volumes:
      - ./almacen:/app
      - ./almacen/tmp/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/almacen?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: almacen
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./almacen/tmp/db:/var/lib/mysql
    