version: '3'
services:
  app:
    image: maven:3.6.0-jdk-8-alpine
    working_dir: /app
    volumes:
      - ./almacen:/app
      - ./almacen/tmp/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    restart: always
    